import { day1 } from './day1';
// import { day1Alt } from './day1-alt'
import { day2 } from './day2';
import { day3 } from './day3';
import { day4 } from './day4';
import { day5 } from './day5';
import { day6 } from './day6';
import { day7 } from './day7';
import { day8 } from './day8';
import { day9 } from './day9';
import { day10 } from './day10';
import { day11 } from './day11';
import { day12 } from './day12';
import { day13 } from './day13';
import { day14 } from './day14';
import { day15 } from './day15';
import { day16 } from './day16';
import { day17 } from './day17';
import { day18 } from './day18';
import { day19 } from './day19';
import { day20 } from './day20';
import { day21 } from './day21';
import { day22 } from './day22';
import { day23 } from './day23';
import { day24 } from './day24';
import { day25 } from './day25';

(async () => {
  await day1();
  // await day1Alt();
  await day2();
  await day3();
  await day4();
  await day5();
  await day6();
  await day7();
  await day8();
  await day9();
  await day10();
  await day11();
  await day12();
  await day13();
  await day14();
  await day15();
  await day16();
  await day17();
  await day18();
  await day19();
  await day20();
  await day21();
  await day22();
  await day23();
  await day24();
  await day25();
})();
